In [20]:
import numpy as np

In [21]:

class Board:
    def __init__(self, arr: np.ndarray) -> None:
        self.board: np.ndarray = arr
        self.marked: np.ndarray = np.zeros_like(self.board)
        self.win_idxs = []
        self.won = False
    
    def __repr__(self) -> str:
        return self.board.__repr__()

    def mark(self, num_called: int) -> None:
        self.marked[self.board == num_called] = 1

    def check(self) -> None:
        for axis in [0, 1]:
            sums = self.marked.sum(axis=axis)
            winning_pos = np.where(sums == 5)[0]
            if winning_pos.shape[0] > 0:
                print("WINNING BOARD:")
                print(self.board)
                print("----------")
        
                if axis==0:
                    print("winning column:")
                    print(f"{axis = }")
                    print(f"{winning_pos = }")
                    print(f"{self.board[:, winning_pos[0]]}")
                else:
                    print("winning row:")
                    print(f"{self.board[winning_pos[0], :]}")
                
                return True

In [22]:
draws = [13,47,64,52,60,69,80,85,57,1,2,6,30,81,86,40,27,26,97,77,70,92,43,94,8,78,3,88,93,17,55,49,32,59,51,28,33,41,83,67,11,91,53,36,96,7,34,79,98,72,39,56,31,75,82,62,99,66,29,58,9,50,54,12,45,68,4,46,38,21,24,18,44,48,16,61,19,0,90,35,65,37,73,20,22,89,42,23,15,87,74,10,71,25,14,76,84,5,63,95]

In [23]:
with open("./data.txt", 'r') as infile:
    lines = infile.readlines()

In [24]:
boards = []
board = []
for line in lines:
    if line=="\n":
        boards.append(np.array(board))
        board = []
    else:
        board.append([int(val) for val in line.rstrip().split()])

boards.append(np.array(board)) 

In [25]:
# assert all(isinstance(b, Board) for b in boards)

In [26]:
def play(draws, boards):
    board_objs = [Board(board) for board in boards]
    for idx, draw in enumerate(draws):
        for board in board_objs:
            if not board.won:
                board.mark(draw)
                if board.check():
                    board.won = True
                    board.win_idxs.append(idx)
                    print(f"{draw = } ({idx}th draw)")
                    print("Game won!")

    return board_objs


winning_boards = play(draws, boards)

WINNING BOARD:
[[81 23  6 14 26]
 [86 42 82 95 85]
 [77 52 38  2 33]
 [69 98 54 37  4]
 [78 39  3 75 80]]
----------
winning column:
axis = 0
winning_pos = array([0])
[81 86 77 69 78]
draw = 78 (25th draw)
Game won!
WINNING BOARD:
[[54 74 32 40 64]
 [ 5 94 71 80 22]
 [82 92 79 93 16]
 [53 33 98 85 14]
 [29 49  9 47 12]]
----------
winning column:
axis = 0
winning_pos = array([3])
[40 80 93 85 47]
draw = 93 (28th draw)
Game won!
WINNING BOARD:
[[98 67  8 10  6]
 [58 13 77 99 81]
 [ 5 55 21 19  1]
 [ 0 26 44 70 93]
 [41 96 31 91 27]]
----------
winning column:
axis = 0
winning_pos = array([4])
[ 6 81  1 93 27]
draw = 93 (28th draw)
Game won!
WINNING BOARD:
[[82 27 25 18 86]
 [73  3 36 28  1]
 [11 96 40 23 93]
 [58 90 88 35 64]
 [ 9 38 69  8 43]]
----------
winning column:
axis = 0
winning_pos = array([4])
[86  1 93 64 43]
draw = 93 (28th draw)
Game won!
WINNING BOARD:
[[62 38 24 44  4]
 [17  8 70 77 86]
 [98  6  9 88 23]
 [85 63 78 60 72]
 [71 48 36 69 81]]
----------
winning row:
[17  8

In [27]:
last_winner_idx = 0
last_winner = None
for board in winning_boards:
    if board.win_idxs[0] > last_winner_idx:
        last_winner_idx = board.win_idxs[0]
        last_winner = board

print(last_winner_idx)
last_winner

85


array([[87, 90, 16, 56, 67],
       [41, 75, 89,  1, 80],
       [22, 62,  5, 45, 69],
       [28, 36, 19, 96, 71],
       [26, 63, 88, 76, 31]])

In [28]:
last_winner.marked

array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1]])

In [29]:
last_winner.board[last_winner.marked==0].sum() * draws[85]

26878

In [9]:
last_winner.win_idxs

[85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

In [ ]:
winning_board.marked
winning_board.board[winning_board.marked == 0].sum() * 78

In [ ]:
arr=np.array([[81, 23,  6, 14, 26],
 [86, 42, 82, 95, 85],
 [77, 52, 38,  2, 33],
 [69, 98, 54, 37,  4],
 [78, 39,  3, 75, 80],
 ])

In [ ]:
arr[:, np.array([0])[0]]

In [ ]:
b.mark(6)
b.check()
b.mark(10)
b.check()
b.mark(3)
b.check()
b.mark(18)
b.check()
b.mark(5)
b.check()

In [ ]:
b.marked